version: '3'
services:
  jenkins:
    build:
      context: ./ 
      dockerfile: dockerfile.jenkins  # Specify your custom Dockerfile name
    container_name: jenkins
    ports:
      - "1010:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker-in-Docker
    restart: always

volumes:
  jenkins_home:
