FROM ubuntu:22.04 AS builder

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    g++ \
    libmysqlcppconn-dev \
    libpthread-stubs0-dev \
    libboost-all-dev \
    libstdc++6 \
    clang \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./src ./src

RUN cd /app/src && ls -al

RUN chmod +x src/build.sh
RUN ./src/build.sh